include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # стиль
    prefer_single_quotes: true
    always_declare_return_types: true
    sort_constructors_first: true

    # читаемость
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true

    # ошибки
    avoid_empty_else: true
    unnecessary_this: true
    unnecessary_null_checks: true

    # архитектура
    avoid_relative_lib_imports: true